protected/controllers/BienvenidoController.php
<?php

/**
 * Description of BienvenidoController
 * Este controlador responde a la solicitudes de usuarios recien registrados
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
class BienvenidoController extends CController{
    
    public $layout='//layouts/columnpasos';
    
    public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','foto',
                                                 'datos'),
				'users'=>array('@'),
                             ),	
                        array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
    public function actionIndex()
    {
        $this->render('index');
    }
    
    public function actionFoto(){
        $model = new Upfoto();
        $src = Yii::app()->request->baseUrl.'/images/user/defaultlarge.gif';       
        $img = null;
        $idFotoActual = Yii::app()->db->createCommand('select foto from adl_perfil where idperfil='.Yii::app()->user->id)->queryRow();
        if(is_numeric($idFotoActual['foto']))
        {
            $img = Foto::model()->findByPk($idFotoActual['foto']);
            if($img != null)
                $src = Yii::app()->request->baseUrl.'/'.$img->thumb_directorio.'/'.$img->thumb_nom;
        }
        
        if(isset($_POST['Upfoto']))
        {
           if(isset($_FILES) and $_FILES['Upfoto']['error']['foto']==0)
            {
                $uf = CUploadedFile::getInstance($model, 'foto');
                $pi = new ProcessorImage($uf,200,180,true);
                if($pi->esValido())
                {
                    if($pi->procesoOK())
                    {
                        $nuevaFoto = new Foto();
                        $nuevaFoto->idperfil = Yii::app()->user->id;
                        $nuevaFoto->nombre = $pi->nombre;
                        $nuevaFoto->descripcion = 'Imagen de perfil';
                        $nuevaFoto->ancho = $pi->rAncho;
                        $nuevaFoto->alto = $pi->rAlto;
                        $nuevaFoto->directorio = $pi->directorioUpload;
                        $nuevaFoto->ruta = $pi->dirUpload;
                        $nuevaFoto->extension = $pi->extension;
                        $nuevaFoto->esfotoperfil = 'SI';
                        
                        $nuevaFoto->thumb_nom = $pi->thumb_nombre;
                        $nuevaFoto->thumb_ancho = $pi->thumb_ancho;
                        $nuevaFoto->thumb_alto = $pi->thumb_alto;
                        $nuevaFoto->thumb_ruta = $pi->dirThumb;
                        $nuevaFoto->thumb_directorio = $pi->directorioThumb;
                        $nuevaFoto->idvisibilidad=  Visibilidad::model()->getIdVisibilidad();
                        $nuevaFoto->idalbum = Cookie::get('idalbum');
                        $nuevaFoto->peso = $_FILES['Upfoto']['size']['foto'];
                        $nuevaFoto->fecha = time();
                        
                        if($nuevaFoto->validate())
                        {
                           if($nuevaFoto->save())
                           {
                               $pf = Perfil::model()->findByPk(Yii::app()->user->id);
                               if($pf != null)
                               {
                                   $pf->foto = $nuevaFoto->idfoto;
                                   $pf->update();
                               }
                                   
                               if($img!=null)
                               {
                                   $img->esfotoperfil = 'NO';
                                   $img->update();
                               }
                                    
                               Yii::app()->user->setFlash('foto_perfil','Foto estabecida');
                               $this->refresh();
                               
                           }
                        }
                    }
                }
            } 
        }
        
        $foto = CHtml::image($src);
        $this->render('foto',array('model'=>$model,'foto'=>$foto));
    }
    
    public function actionDatos()
    {
        $model=Perfil::model()->findByPk(Yii::app()->user->id);

        // uncomment the following code to enable ajax-based validation
        /*
        if(isset($_POST['ajax']) && $_POST['ajax']==='perfil-datos-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        */

        if(isset($_POST['Perfil']))
        {
            $model->attributes=$_POST['Perfil'];
            if($model->validate())
            {
                $model->update();
                $this->refresh();
            }
        }
        $this->render('datos',array('model'=>$model));
    }
}

?>

protected/controllers/PerfilController.php
<?php
/**
 * Description of PerfilController
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
class PerfilController extends CController{
   
    public $layout='//layouts/columnperfil';
    
        public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','albums',
                                                  'amigos',
                                                  'estados',
                                                  'posts',
                                                  'publicarEstado'),
				'users'=>array('@'),
                             ),	
                        array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
    
    
    
    public function actionIndex($id)
    {
        if(is_numeric($id))
        {
            $pf = Perfil::model()->findByPk($id);
           $foto=$pf->getFoto(); 
          $this->render('index',array('foto'=>$foto));  
        }else
            throw new CHttpException(404,'La pagina solicitada no existe');
        
    }
    
    public function actionPublico($id)
    {
        
    }
    
    public function actionAlbums()
    {
        $this->renderPartial('_items/albums');
    }
    
    public function actionAmigos()
    {
       $this->renderPartial('_items/amigos'); 
    }
    
    public function actionEstados()
    {
        $model=new Estado('register');
        $this->renderPartial('_items/estados',array('model'=>$model));
    }
    
    public function actionPosts()
    {
        $this->renderPartial('_items/posts');
    }
    
    public function actionPublicarEstado()
    {
        $model=new Estado('register');

        // uncomment the following code to enable ajax-based validation
        /*
        if(isset($_POST['ajax']) && $_POST['ajax']==='estado-_formestado-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        */

        if(isset($_POST['Estado']))
        {
            $model->attributes=$_POST['Estado'];
            if($model->validate())
            {
                // form inputs are valid, do something here
                return;
            }
        }
        $this->render('_formestado',array('model'=>$model));
    }
    
}

?>

protected/views/bienvenido/datos.php
<div class="portlet span-10">
  <div class="portlet-content">  
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'perfil-datos-form',
        'htmlOptions'=>array('class'=>'formee'),
	'enableAjaxValidation'=>false,
        'enableClientValidation'=>true,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>
<fieldset>
    <legend>Cuentanos algo de ti</legend>
	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'login'); ?>
		<?php echo $form->textField($model,'login'); ?>
		<?php echo $form->error($model,'login'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'s_sentimental'); ?>
		<?php echo $form->dropDownList($model,'s_sentimental',DefinidorTipos::situacionSentimental(),
                                                array(
                                                    'options'=>array($model->s_sentimental=>array('selected'=>true)),
                                                    'empty'=>'¿Cuál es tu situacion sentimental?'
                                                )); ?>
		<?php echo $form->error($model,'s_sentimental'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'intereses'); ?>
		<?php echo $form->dropDownList($model,'intereses',DefinidorTipos::preferencia(),array(
                                                    'options'=>array($model->intereses=>array('selected'=>true)),
                                                    'empty'=>'¿Prefieres?'
                                                
                                                )); ?>
		<?php echo $form->error($model,'intereses'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fono'); ?>
		<?php echo $form->textField($model,'fono'); ?>
		<?php echo $form->error($model,'fono'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'movil'); ?>
		<?php echo $form->textField($model,'movil'); ?>
		<?php echo $form->error($model,'movil'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'nextel'); ?>
		<?php echo $form->textField($model,'nextel'); ?>
		<?php echo $form->error($model,'nextel'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'descripcion'); ?>
		<?php echo $form->textArea($model,'descripcion'); ?>
		<?php echo $form->error($model,'descripcion'); ?>
	</div>
        <div class="row">
		<?php echo $form->labelEx($model,'especialidad_social'); ?>
		<?php echo $form->textArea($model,'especialidad_social'); ?>
		<?php echo $form->error($model,'especialidad_social'); ?>
	</div>
        <div class="row">
		<?php echo $form->labelEx($model,'frase'); ?>
		<?php echo $form->textArea($model,'frase'); ?>
		<?php echo $form->error($model,'frase'); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>
</fieldset>
<?php $this->endWidget(); ?>

</div><!-- form -->
 <div class="clearfix"></div>
       <?php echo CHtml::link('Continuar',array('perfil/index','id'=>Yii::app()->user->id),array('class'=>'btn btn-small'));?>   
           
</div>
 </div>   

protected/views/bienvenido/foto.php
<?php if(Yii::app()->user->hasFlash('foto_perfil')){?>
<div class="flash-success"><?php echo Yii::app()->user->getFlash('foto_perfil')?></div>
<?php } ?>
<div class="portlet span-18">
    <div class="portlet-header"><h4>Foto para tu perfil(RECOMENDADO)</h4></div>
    <div class="portlet-content"> 
        <div class="portlet span-6">
            <div class="portlet-content">
                <?php                
                    echo $foto;                   
                ?>
            </div>    
        </div>
        <div class="portlet span-10">
            <div class="portlet-content">
                <div class="form"> 

        <?php $form=$this->beginWidget('CActiveForm', array(
                'id'=>'ufoto-registro-form',
                'enableClientValidation'=>true,
                'htmlOptions'=>array('enctype'=>'multipart/form-data','class'=>'formee'),
                'enableAjaxValidation'=>false,
        )); ?>

            <fieldset>               

                <?php echo $form->errorSummary($model); ?>

                <div class="uploader">
                        <?php echo $form->labelEx($model,'foto'); ?>
                        <?php echo CHtml::hiddenField('MAX_FILE_SIZE', '6291456'); ?>
                        <?php echo $form->fileField($model,'foto'); ?>
                        <?php echo $form->error($model,'foto'); ?>
                </div>               

                <div class="row buttons">
                        <?php echo CHtml::submitButton('Subir Foto'); ?>
                </div>
        </fieldset>
        <?php $this->endWidget(); ?>

        </div><!-- form -->
                <div class="clearfix"></div>
             <?php echo CHtml::link('Continuar',array('datos'),array('class'=>'btn btn-small'));?>   
               
            </div>    
        </div>  
        
    </div>          
</div> 

protected/views/bienvenido/index.php
<div class="portlet span-18">
    <div class="portlet-header"><h4>Invita a tus amigos</h4></div>
    <div class="portlet-content"> 
        <?php echo CHtml::link('Omitir',array('foto'));?>
    </div>          
</div>       