protected/modules/anonimo/controllers/PostController.php
<?php
/**
 * Description of PostController
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
class PostController extends CController{
   
    public function actionIndex($wsearch)
    {
        if(strlen($wsearch)>0)
        {
            $post = Apost::model()->postEncontrados($wsearch);
            $this->render('listaposts',array('criterio'=>$post));
        }else
            $this->redirect (array('default/index'));
    }
    
    public function actionCategoria($id)
    {
        if(is_numeric($id))
        {
            $post = Apost::model()->postsPorCategoria($id);
            $this->render('listaposts',array('criterio'=>$post));            
        }
    }
    
    public function actionPublicaciones()
    {
        $datos = Apost::todosPost();
        $this->render('todos',array(
            'posts'=>$datos['posts'],
            'pages'=>$datos['pages'],
        ));
    }
    
    public function actionImagenes()
    {
          $post = Apost::model()->imgenesDeposts();
          $this->render('listarImagenespost',array('criterio'=>$post));         
    }
    
    public function actionEtiquetas($tag)
    {
        if($tag == '')
            throw new CHttpException(404,'Error!');
        $criteria=new CDbCriteria(array(			
			'order'=>'fecha DESC',			
		));
		
        $criteria->addSearchCondition('etiquetas',$tag);

		$dataProvider=new CActiveDataProvider('Apost', array(
			'pagination'=>array(
				'pageSize'=>15
			),
			'criteria'=>$criteria,
		));

		$this->render('listaposts',array(
			'criterio'=>$dataProvider,
		));
    }
    
}

?>

protected/modules/anonimo/views/post/_imagenespost.php
<li>
    <?php 
        $img = Aimagen::model()->findByPk($data->idimagen);
        if($img != null)
        {
            $src = Yii::app()->request->baseUrl.'/'.$img->thumb_directorio.'/'.$img->nom_thumb;
            echo CHtml::link(CHtml::image($src),array('/anonimo/default/post',
                                                              'id'=>$data->idpost,
                                                              'pagina'=>Util::eliminarSignos($data->titulo)));
        }
    ?>
</li>    

protected/modules/anonimo/views/post/buscar.php
<div class="btn btn-mediun" style="float:right;">
<?php

echo CHtml::beginForm(Yii::app()->getController()->createUrl('post/index'),'GET', array());
echo CHtml::label('Buscar contenido: ', 'wsearch');
echo CHtml::textField('wsearch','',array('size'=>'38px'));
echo CHtml::submitButton('Buscar');
echo CHtml::endForm();
?>
</div>

protected/modules/anonimo/views/post/item.php
<div class="portlet span-24">
    <div class="portlet-header"><h4><?php echo CHtml::link($data->titulo,array('/anonimo/default/post','id'=>$data->idpost,'pagina'=>  Util::eliminarSignos($data->titulo)));?></h4>
    <ul class="portlet-tab-nav">
        <li class="portlet-tab-nav-active"><?php echo CHtml::link('VER POST COMPLETO',array('/anonimo/default/post','id'=>$data->idpost,'pagina'=>  Util::eliminarSignos($data->titulo)));?>
        </li>
        <li class="portlet-tab-nav-active"><a>Comentarios (
                <?php echo Acomentario::model()->count('id_del_comentado='.$data->idpost)?> )
            </a>
        </li>
    </ul>
    </div>
    <?php foreach($data->getTagLinks() as $etiqueta)
                echo $etiqueta." ";
           ?>
    <div class="portlet-content">        
        <div class="content-flow">
        <?php echo $data->contenido;?>
        </div>    
    </div>    
</div> 

protected/modules/anonimo/views/post/listaposts.php
<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$criterio,
	'itemView'=>'item',
));?>

protected/modules/anonimo/views/post/listarImagenespost.php
<?php $this->widget('zii.widgets.CListView', array(
        'itemsTagName'=>'ul',
        'htmlOptions'=>array('class'=>'gallery'),
	'dataProvider'=>$criterio,
	'itemView'=>'_imagenespost',
        'template'=>'{summary}{pager}{items}\n',
        
)); ?>
<div class="clear"></div>

protected/modules/anonimo/views/post/todos.php
<div id="posts" class="portlet-content" style="padding: 10px 50px 4px 50px;">
<?php foreach($posts as $data){?>
<div class="portlet span-24 apost">
    <div class="portlet-header"><h4><?php echo CHtml::link($data->titulo,array('/anonimo/default/post','id'=>$data->idpost,'pagina'=>  Util::eliminarSignos($data->titulo)));?></h4>
    <ul class="portlet-tab-nav">
        <li class="portlet-tab-nav-active"><?php echo CHtml::link('VER POST COMPLETO',array('/anonimo/default/post','id'=>$data->idpost,'pagina'=>  Util::eliminarSignos($data->titulo)));?>
        </li>
        <li class="portlet-tab-nav-active"><a>Comentarios (
                <?php echo Acomentario::model()->count('id_del_comentado='.$data->idpost)?> )
            </a>
        </li>
    </ul>
    </div>
    <?php foreach($data->getTagLinks() as $etiqueta)
                echo $etiqueta." ";
           ?>
    <div class="portlet-content">        
        <div class="content-flow">
        <?php echo $data->contenido;?>
        </div>    
    </div>    
</div> 
<?php } ?>
</div> 
<div class="clear"></div>
<?php $this->widget('ext.yiinfinite-scroll.YiinfiniteScroller', array(
    'contentSelector' => '#posts',
    'itemSelector' => 'div.apost',
    'loadingText' => 'Cargando mas publicacione.......',
    'donetext' => 'Parece que ya no hay mas publicciones :(',
    'pages' => $pages,
)); ?>