protected/models/Perfil.php
<?php

/**
 * This is the model class for table "adl_perfil".
 *
 * The followings are the available columns in table 'adl_perfil':
 * @property string $idperfil
 * @property string $login
 * @property string $foto
 * @property string $s_sentimental
 * @property string $frase
 * @property string $especialidad_social
 * @property string $intereses
 * @property string $descripcion
 * @property string $fono
 * @property string $movil
 * @property string $nextel
 *
 * The followings are the available model relations:
 * @property Usuario $idperfil0
 */
class Perfil extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Perfil the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'adl_perfil';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
                        array('login','unique'),
                        array('login','match','pattern'=>'/^[a-zA-Z0-9]\w+[a-zA-Z0-9]$/x'),
			array('login, frase', 'length', 'max'=>250),
                        array('foto', 'length', 'max'=>20),
                        array('s_sentimental','length','max'=>10),
			array('intereses', 'length', 'max'=>1),
			array('especialidad_social', 'length', 'max'=>300),
			array('fono, movil, nextel', 'length', 'max'=>15),
                        array('fono','match','pattern'=>'/^(\(\d{3}\)[-. ]?|\d{3}[-. ]?)?\d{3}[-. ]\d{4}$/x'),
                        array('nextel','match','pattern'=>'/^\d{3}\*\d{4}$/x'),
                        array('movil','length','min'=>9),
                        array('movil','match','pattern'=>'/^\d+$/'),
			array('descripcion', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('idperfil, login, foto, s_sentimental, frase, especialidad_social, intereses, descripcion, fono, movil, nextel', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'idperfil0' => array(self::BELONGS_TO, 'Usuario', 'idperfil'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'idperfil' => 'Idperfil',
			'login' => 'Login(nombre de usuario)',
			'foto' => 'Foto',
			's_sentimental' => 'Situación Sentimental',
			'frase' => 'Tu Frase favorita',
			'especialidad_social' => 'Tu Especialidad Social',
			'intereses' => '¿Te Interesan?',
			'descripcion' => 'Descripcion',
			'fono' => 'Telefono (ejem: (051)123-1235, 123-1235)',
			'movil' => 'Movil(Celular)',
			'nextel' => 'Nextel',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('idperfil',$this->idperfil,true);
		$criteria->compare('login',$this->login,true);
		$criteria->compare('foto',$this->foto,true);
		$criteria->compare('s_sentimental',$this->s_sentimental,true);
		$criteria->compare('frase',$this->frase,true);
		$criteria->compare('especialidad_social',$this->especialidad_social,true);
		$criteria->compare('intereses',$this->intereses,true);
		$criteria->compare('descripcion',$this->descripcion,true);
		$criteria->compare('fono',$this->fono,true);
		$criteria->compare('movil',$this->movil,true);
		$criteria->compare('nextel',$this->nextel,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
        
        public function getFoto()
        {
            $src = Yii::app()->request->baseUrl.'images/user/defaultmedium.gif';
            if(is_numeric($this->foto))
            {
                $foto = Foto::model()->findByPk($this->foto);
               if($foto != null)
               {
                   $src = Yii::app()->request->baseUrl.'/'.$foto->thumb_directorio.'/'.$foto->thumb_nom;
               }
            }
            
            return CHtml::image($src);
        }
}

protected/controllers/PerfilController.php
<?php
/**
 * Description of PerfilController
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
class PerfilController extends CController{
   
    public $layout='//layouts/columnperfil';
    
        public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','albums',
                                                  'amigos',
                                                  'estados',
                                                  'posts',
                                                  'publicarEstado'),
				'users'=>array('@'),
                             ),	
                        array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
    
    
    
    public function actionIndex($id)
    {
        if(is_numeric($id))
        {
            $pf = Perfil::model()->findByPk($id);
           $foto=$pf->getFoto(); 
          $this->render('index',array('foto'=>$foto));  
        }else
            throw new CHttpException(404,'La pagina solicitada no existe');
        
    }
    
    public function actionPublico($id)
    {
        
    }
    
    public function actionAlbums()
    {
        $this->renderPartial('_items/albums');
    }
    
    public function actionAmigos()
    {
       $this->renderPartial('_items/amigos'); 
    }
    
    public function actionEstados()
    {
        $model=new Estado('register');
        $this->renderPartial('_items/estados',array('model'=>$model));
    }
    
    public function actionPosts()
    {
        $this->renderPartial('_items/posts');
    }
    
    public function actionPublicarEstado()
    {
        $model=new Estado('register');

        // uncomment the following code to enable ajax-based validation
        /*
        if(isset($_POST['ajax']) && $_POST['ajax']==='estado-_formestado-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        */

        if(isset($_POST['Estado']))
        {
            $model->attributes=$_POST['Estado'];
            if($model->validate())
            {
                // form inputs are valid, do something here
                return;
            }
        }
        $this->render('_formestado',array('model'=>$model));
    }
    
}

?>

protected/views/perfil/_formestado.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'estado-_formestado-form',
        'htmlOptions'=>array('class'=>'formee'),
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>

		
		<?php echo $form->hiddenField($model,'idperfil',array('value'=>Yii::app()->user->id)); ?>
		<?php echo $form->hiddenField($model,'fecha',array('value'=>time())); ?>
                <?php echo $form->hiddenField($model,'content_link'); ?>

	<div class="row">		
		<?php echo $form->textArea($model,'contenido'); ?>
		<?php echo $form->error($model,'contenido'); ?>
	</div>	

	<div class="row  grid-5-12 clear">
		<?php echo $form->labelEx($model,'idvisibilidad'); ?>
		<?php echo $form->dropDownList($model,'idvisibilidad',DefinidorTipos::tipoVisivilidad(),array('style'=>'height:35px;')); ?>
		<?php echo $form->error($model,'idvisibilidad'); ?>
	</div>

	<div class="row buttons clear" >
		<?php echo CHtml::submitButton('Publicar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/perfil/index.php
<div class="span-24">
<div class="span-6 portlet">
    <div class="portlet-content">
    <?php echo $foto;?>
     </div>   
</div>    
<div class="span-15">
    
<?php
$this->widget('zii.widgets.jui.CJuiTabs', array(
      'tabs'=>array(
          'Estados'=>array('ajax'=>$this->createUrl('perfil/estados')),
          'Fotos'=>array('ajax'=>$this->createUrl('perfil/albums')),
          'Amigos'=>array('ajax'=>$this->createUrl('perfil/amigos')),
          'Posts'=>array('ajax'=>$this->createUrl('perfil/posts')),
          
      ),
      // additional javascript options for the tabs plugin
      'options'=>array(
          'collapsible'=>true,
      ),
  ));

?>
</div>
</div>    