protected/modules/anonimo/controllers/DefaultController.php
<?php

class DefaultController extends Controller
{
    
        public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFAABB,
			),
			
		);
	}
        
        public function actionPostear()
        {
             $model=new Apost('register');
             
             if(isset($_POST['Apost']))
                {                    
                    $model->attributes = $_POST['Apost'];
                    
                    $sizePermitido = 2172864;
                    
                    if(!Yii::app()->user->isGuest)
                        $sizePermitido = 6291456; 
                    
                    if(isset($_FILES) and $_FILES['Apost']['error']['imagen']==0 and
                           $_FILES['Apost']['size']['imagen']<= $sizePermitido )
                    {
                        $uf = CUploadedFile::getInstance($model, 'imagen');
                        $pi = new ProcessorImage($uf);
                        if($pi->esValido())
                        {
                            if($pi->procesoOK())
                            {
                                
                                $imagen = new Aimagen();
                                $imagen->nombre_original = $pi->nombreOrginal;
                                $imagen->nombre = $pi->nombre;
                                $imagen->descripcion = $_POST['Apost']['titulo'];
                                $imagen->extension = $pi->extension;
                                $imagen->ruta = $pi->dirUpload;
                                $imagen->directorio = $pi->directorioUpload;
                                $imagen->ancho = $pi->rAncho;
                                $imagen->alto = $pi->rAlto;
                                
                                $imagen->nom_thumb = $pi->thumb_nombre;
                                $imagen->thumb_ruta = $pi->dirThumb;
                                $imagen->thumb_directorio = $pi->directorioThumb;
                                $imagen->thumb_alto = $pi->thumb_alto;
                                $imagen->thumb_ancho = $pi->thumb_ancho;
                                
                                $imagen->tipo = DefinidorTipos::$TIPO_ADJUNTA;
                                $imagen->enpost = 1;
                                $imagen->idCategoria = $_POST['Apost']['idcategoria'];
                                $imagen->fecha =time();
                                
                                if($imagen->save(true))
                                {
                                    $model->idimagen = $imagen->idimagen;                                   
                                }else{
                                    echo $imagen->extension;
                                    print_r($imagen->getErrors());
                                    return;
                                }
                                    
                                
                            }
                                
                        }else
                        {
                            Yii::app()->user->setFlash('img-error',$_FILES['Apost']['name']['imagen'].' no es un archivo valido');
                           $this->render('post',array('model'=>$model));
                           return;
                        }
                            
                        
                    }
                       //q print_r($_FILES);
                    /*
                    $model->attributes=$_POST['Apost'];
                    */
                    if($model->validate())
                    {
                        if($model->save())
                        {
                            if(is_numeric($model->idimagen))
                            {
                                Cookie::set('ipost', $model->idpost);
                                Cookie::set('ipag', Util::eliminarSignos($model->titulo));
                            }
                           $this->redirect(array('post','id'=>$model->idpost,'pagina'=>Util::eliminarSignos($model->titulo)), true); 
                        }                            
                        else
                            print_r ($model->getErrors());
                    }
                }
             
             
             $this->render('post',array('model'=>$model,'categoria'=>'General'));
        }
    
	public function actionIndex()
	{               
                $this->setPageTitle(CHtml::encode(Yii::app()->name).' - anonimo');
                $this->render('index');		
	}
        
        /**
	 * Suggests tags based on the current user input.
	 * This is called via AJAX when the user is entering the tags input.
	 */
	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=  Aetiquetas::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}
        
       public function actionPost($id,$pagina)
       {
           if(is_numeric($id) and is_string($pagina) and $pagina != '')
           {
             $post = Apost::model()->findByPk($id);
             $comentario=new Acomentario;
             if($post != null)
             {
                 if($pagina == Util::eliminarSignos($post->titulo))
                 {                     
                    $this->render('verpost',array('model'=>$post,'comentario'=>$comentario)); 
                 }else
                    throw new CHttpException(404,'El post ningun post con ese titulo.');
                 
             }else
               throw new CHttpException(404,'El post que solicita no existe.');
               
           }else
               throw new CHttpException(404,'La página solicitada no existe.');
       }
       
       public function actionComentar()
       {
           $model=new Acomentario;

            // uncomment the following code to enable ajax-based validation
            /*
            if(isset($_POST['ajax']) && $_POST['ajax']==='acomentario-_form-form')
            {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }
            */

            if(isset($_POST['Acomentario']))
            {
                $model->attributes=$_POST['Acomentario'];
                if($model->validate())
                {
                    if($model->save())
                    {
                      Yii::app()->user->setFlash('comentario-ok','Comentario Agregado');  
                      $this->redirect(array('post','id'=>$model->id_del_comentado,'pagina'=>$model->tituloPost));  
                    }                       
                    
                }else
                {
                   print_r($model->getErrors()); 
                }
                    
            }
       }
       
       
       public function actionDenuncia()
    {
        $model=new Areportados('insert');

        // uncomment the following code to enable ajax-based validation
        /*
        if(isset($_POST['ajax']) && $_POST['ajax']==='areportados-denuncia-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        */

        if(isset($_POST['Areportados']))
        {
            $model->attributes=$_POST['Areportados'];
            if($model->validate())
            {
              $model->save();
               $this->redirect(array('post','id'=>$_POST['Areportados']['idreportado'],'pagina'=>$_POST['Areportados']['titulo']));
            }
        }
       $this->redirect(array('index')); 

    }
    
}

protected/modules/anonimo/controllers/PostController.php
<?php
/**
 * Description of PostController
 *
 * @author El APRENDIZ www.elaprendiz.net63.net
 */
class PostController extends CController{
   
    public function actionIndex($wsearch)
    {
        if(strlen($wsearch)>0)
        {
            $post = Apost::model()->postEncontrados($wsearch);
            $this->render('listaposts',array('criterio'=>$post));
        }else
            $this->redirect (array('default/index'));
    }
    
    public function actionCategoria($id)
    {
        if(is_numeric($id))
        {
            $post = Apost::model()->postsPorCategoria($id);
            $this->render('listaposts',array('criterio'=>$post));            
        }
    }
    
    public function actionPublicaciones()
    {
        $datos = Apost::todosPost();
        $this->render('todos',array(
            'posts'=>$datos['posts'],
            'pages'=>$datos['pages'],
        ));
    }
    
    public function actionImagenes()
    {
          $post = Apost::model()->imgenesDeposts();
          $this->render('listarImagenespost',array('criterio'=>$post));         
    }
    
    public function actionEtiquetas($tag)
    {
        if($tag == '')
            throw new CHttpException(404,'Error!');
        $criteria=new CDbCriteria(array(			
			'order'=>'fecha DESC',			
		));
		
        $criteria->addSearchCondition('etiquetas',$tag);

		$dataProvider=new CActiveDataProvider('Apost', array(
			'pagination'=>array(
				'pageSize'=>15
			),
			'criteria'=>$criteria,
		));

		$this->render('listaposts',array(
			'criterio'=>$dataProvider,
		));
    }
    
}

?>

protected/modules/anonimo/views/default/comentar.php
<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>

protected/modules/anonimo/views/default/index.php
<?php
$this->breadcrumbs=array(
	$this->module->id,
);

?>
<div class="portlet span-22 categorias"> 
         <div class="portlet-header"><h4>CATEGORIAS</h4>
            <ul class="portlet-tab-nav">
                <li class="portlet-tab-nav-active">
                    <?php echo CHtml::link("VER TODAS LAS PUBLICACIONES", array('post/publicaciones'))?>
                </li>
            </ul>
         </div>
         <div class="portlet-content">
     <?php 
        $categorias = Yii::app()->db->createCommand("select idcategoria, nombre from acategoria")->queryAll();
     ?>   
        
     <?php foreach($categorias as $categoria1){?>
        
        <?php echo CHtml::link($categoria1['nombre'], array('post/categoria','id'=>$categoria1['idcategoria']), array('class'=>'btn btn-small'))?>
        
     <?php }?>
          </div>   
 </div>

    
<div class="box-imagen portlet span-22">
    <div class="portlet-content"> 
    
    <?php $this->widget('ImagenesPopulares', array(
				//'maxTags'=>Yii::app()->params['tagCloudCount'],
        )); ?>  
     <?php $this->widget('UltimosPost', array(
				//'maxTags'=>Yii::app()->params['tagCloudCount'],
        )); ?>   
    
    <?php $this->widget('ComentariosRecientes', array(
				//'maxTags'=>Yii::app()->params['tagCloudCount'],
        )); ?> 
        
    <?php $this->widget('EtiquetasNube', array(
				//'maxTags'=>Yii::app()->params['tagCloudCount'],
        )); ?>
        
       
    </div>
</div>

protected/modules/anonimo/views/default/post.php
<div class="f-registro portlet span-20">
<div class="form portlet-content">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'apost-post-form',
        'enableClientValidation'=>true,
        'htmlOptions'=>array('enctype'=>'multipart/form-data','class'=>'formee'),
	'enableAjaxValidation'=>false,
        'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>
    <fieldset>
        <legend>Postear</legend>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

        <div class="row">
		<?php echo $form->labelEx($model,'user_nom'); ?>
		<?php echo $form->textField($model,'user_nom'); ?>
		<?php echo $form->error($model,'user_nom'); ?>
	</div>
        
	<div class="row">
		<?php echo $form->labelEx($model,'imagen'); ?>
		<?php echo $form->fileField($model,'imagen'); ?>
                <p class="hint">JPEG,GIF O PNG, tamaño maximo: 
                    <?php echo !Yii::app()->user->isGuest?'5MB':'2MB'; ?></p>
		<?php echo $form->error($model,'imagen'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'titulo'); ?>
		<?php echo $form->textField($model,'titulo'); ?>
		<?php echo $form->error($model,'titulo'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'contenido'); ?>
		<?php echo $form->textArea($model,'contenido',array('class'=>'tinymce','style'=>'height:600px;')); ?>
		<?php echo $form->error($model,'contenido'); ?>
	</div>
        <div class="row">
		<?php echo $form->labelEx($model,'idcategoria'); ?>
		<?php echo $form->dropDownList($model,'idcategoria',  Acategoria::getListCategoria(),
                        array(
                    'options'=>array($model->idcategoria=>array('selected'=>true)                        
                    ),                    
                    'empty'=>'Categorias:')
                        ); ?>
		<?php echo $form->error($model,'idcategoria'); ?>
	</div>

	<div class="row">		
                <?php echo $form->labelEx($model,'etiquetas'); ?>
		<?php $this->widget('CAutoComplete', array(
			'model'=>$model,
			'attribute'=>'etiquetas',
			'url'=>array('suggestTags'),
			'multiple'=>true,
			'htmlOptions'=>array('size'=>50),
		)); ?>
		<p class="hint">Please separate different tags with commas.</p>
		<?php echo $form->error($model,'etiquetas'); ?>
            
            
            
                <?php echo $form->hiddenField($model,'tipo',array('value'=>DefinidorTipos::$TIPO_PULICACION)); ?>		
                <?php echo $form->hiddenField($model,'fecha',array('value'=>time())); ?>
                
	
	</div>
        <?php if(Yii::app()->user->isGuest){
            if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'ccaptcha'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'ccaptcha'); ?>
		</div>
		<div class="hint" style="color: blue;">Genere un codigo nuevo y escriba el texto que se muestra</div>
		<?php echo $form->error($model,'ccaptcha'); ?>
	</div>
	<?php endif; 
        }?>

	<div class="row">
		<?php echo $form->labelEx($model,'contrasenia'); ?>
		<?php echo $form->passwordField($model,'contrasenia'); ?>
		<?php echo $form->error($model,'contrasenia'); ?>
	</div>


	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>
        </fieldset>

<?php $this->endWidget(); ?>

</div><!-- form -->
</div>

protected/modules/anonimo/views/default/verpost.php
<div class="portlet span-22">
    <div class="portlet-header"><h4><?php echo $model->titulo; ?></h4>
    <ul class="portlet-tab-nav">
     <li class="portlet-tab-nav-active">  
     <?php echo CHtml::link("VER MAS PUBLICACIONES", array('post/publicaciones'))?>
         </li>
        <li class="portlet-tab-nav-active"><a href="#f-coment">Comentar </a></li>				
        <li class="portlet-tab-nav-active"><?php 
        echo CHtml::link('Reportar', array('#'), array('onclick'=>'$("#aviso").dialog("open"); return false;'));
        ?></li>
    </ul>
    </div>
    <?php 
            foreach($model->getTagLinks() as $etiquetas)
                echo $etiquetas." ";
    ?>
    <div class="portlet-content">
        <?php if($model->tieneImagen){?>
            <?php echo $model->getImagen(450,350);?>
        <?php }?>
        <?php echo $model->contenido; ?>
    </div>
</div>
<div class="clearfix"></div>
<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$comentario->comentariosDePost($model->idpost),
	'itemView'=>'/comentario/item',
)); ?>
<div class="portlet span-12">
    <div class="portlet-header"><h4><a name="f-coment">Comentar</a></h4></div>
     <div class="portlet-content">
     <?php if(Yii::app()->user->hasFlash('comentario-ok')){?>  
         <div class="flash-success">
             <?php echo Yii::app()->user->getFlash('comentario-ok'); ?>
         </div>
     <?php } ?>        
<?php
$this->renderPartial('/comentario/_form',array('model'=>$comentario,
                                                'post'=>$model->idpost,'titulo'=>$model->titulo));
?>
     </div>
</div>
<?php
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
      'id'=>'aviso',
      // additional javascript options for the dialog plugin
      'options'=>array(
          'title'=>'Denuncia',
          'autoOpen'=>false,
      ),
  ));
$model=new Areportados('insert');
echo $this->renderPartial('/reportados/denuncia',array('model'=>$model,'id'=>$_GET['id'],'pagina'=>$_GET['pagina']),true);
?>
 
<?php
  $this->endWidget('zii.widgets.jui.CJuiDialog');

?>